#!/bin/bash

system_type=$(uname -s)

# APT

if [ "$system_type" = "Linux" ]; then

  echo "Installing packages"  
  sudo apt-get -y install universal-ctags curl git nodejs vim wget zsh zsh-autosuggestions
fi
