#!/bin/bash

system_type=$(uname -s)

if [ ! -d "$HOME/.oh-my-zsh" ]; then
  echo "Installing Oh My Zsh"
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended

  echo "Installing MNML theme"
  curl -fsSL https://raw.githubusercontent.com/thijskok/zsh-theme/master/mnml.zsh-theme -o "$HOME/.oh-my-zsh/themes/mnml.zsh-theme"

  if [ "$system_type" == "Linux" ]; then
    if [ ! -d "${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions" ]; then
      echo "Installing ZSH autosuggestions"  
      git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
    fi
  fi

  echo "Setting up Oh My Zsh"
  cp ~/.zshrc-defaults ~/.zshrc
fi


